### ISSUE TITLE
Tagging temporal expressions

### ISSUE THREAD

**Issue by sanmai-NL** [proycon/frogdata#1]
I was wondering whether you have plans to add training data for tagging of temporal expressions. That's dependent on an annotation scheme, and I haven't found a standard one for Dutch so far. I have read SoNaR 500 contains semantic annotations of temporal expressions. In case you are interested in including such data for Frog, but are not working on it, do you prefer a certain annotation scheme?

**Comment by antalvdb** [comment]
The plan is to include the Heideltime tagger, or a named-entity tagger based on MBT that implements (most of) the Heideltime functionality. A Dutch version of the Heideltime tagger was developed by our team member Matje van de Camp (https://github.com/HeidelTime/heideltime). In her Ph.D. thesis she also developed her own time expression tagger. Some of this is bound to end up in Frog.

Heideltime adopts the TIMEX3 annotation standard.

**Comment by kosloot** [comment]
Closing this. Work on this is stopped due to lack of recources.
