### ISSUE TITLE
Build fails when a _ is present the LaMachine installation name

### ISSUE THREAD

**Issue by szindel** [proycon/frogdata#6]
Build fails when a _ is present the LaMachine installation name

/dev/fd/63: line 1515: cd: y/lamachine-controller/LaMachine_sz/LaMachine: No such file or directory
fatal: not a git repository (or any of the parent directories): .git
cp: y/lamachine-LaMachine_sz.yml: No such file or directory
================ FATAL ERROR ==============
An error occurred during installation!!
Unable to copy y/lamachine-LaMachine_sz.yml

**Comment by proycon** [comment]
Can you send me a bit more of the log? I'm currently unsure what is reporting this and how this relates to frogdata.
Do things work fine when your LaMachine name does not use an underscore?

**Comment by kosloot** [comment]
Assuming this is a non-issue now.
